spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/wxorder?characterEncoding=utf-8&sueSSL=false
eureka:
  client:
    service-url:
      defaultZone: http:localhost:8761/eureka/
